### ISSUE TITLE
Facing issues while resetting mc g02 chip

### ISSUE THREAD

**Issue by KamleshPatilishere** [wangyu-/canon_mc-g02_resetter#1]
I'm using canon pixma g3060 printer. While resetting the maintenance cartridge mc g02 I found the solution on this website. Which is fascinating...  I uploaded the read program and saved the serial monitor data but, messing with write program. Arduino and programing is new to me. Pls help me with this.

**Comment by wangyu-** [comment]
This issue was solved by emails. It turned out to be bad dump first, and mistakes in the procedure later.


-----------------------
by the way, don't send me emails, post an issue instead.  I no longer accept debug your usage via emails
