### ISSUE TITLE
Bad dump

### ISSUE THREAD

**Issue by Nickduino** [wangyu-/canon_mc-g02_resetter#3]
I'm an idiot for not double checking my dump when reading it (I know the instructions call for that). Now I wrote the wrong dump and I obviously can't read it anymore. The printer doesn't recognize the cartridge.

Here's the dump of my mg-g01:
`FF,0xEC,0x9A,0x50,0x04,0xDC,0x14,0xD1,0x45,0xDD,0x55,0xC2,0x57,0x2B,0xBE,0x27,0xD2,0x6A,0x1E,0xA7,0xAC,0x11,0x0E,0x65,0x62,
0x4C,0x93,0x3F,0x1B,0xC2,0x5D,0x12,0xEC,0xDF,0x6E,0x59,0xA2,0x22,0x7C,0x49,0x4F,0x23,0x92,0x87,0xA8,0xC1,0xF5,0xDA,0x2A,0xA5,0x24,0x21,0x6E,0x7D,0xF8,0xF2,0xEE,
0x2A,0xD7,0x6F,0xE9,0x5C,0x98,0x85,0xFF,0xCD,0xAC,0x9E,0xA2,0xA2,0x6C,0xF6,0x37,0x2E,0x16,0x11,0x4B,0xA0,0x89,0xF4,0x1D,0x6E,0x94,0x54,0xC7,0xBD,0x60,0xCE,0x86,
0x47,0x31,0x19,0x4C,0x68,0x69,0x6A,0xEB,0x99,0xAC,0x98,0x68,0x4D,0xF2,0xEE,0x61,0x20,0x98,0x40,0x63,0xA2,0x1A,0x62,0xA4,0x8E,0x96,0xE8,0x3C,0xF8,0x8B,0xA0,0x80,
0xA1,0xBB,0x6D,0x05,0xB5,0xEA,0xB3,0xDA,0xC5,0xFE,0xAE,0xC3,0x25,0x22,0x73,0x53,0xCB,0x19,0xA1,0x62,0x31,0x0A,0x9D,0xD8,0xE1,0x20,0x7B,0xBC,0x08,0xBF,0xCA,0xC5,
0x22,0x9B,0xBB,0xBA,0x0E,0xFB,0x05,0xB2,0x63,0xAC,0x23,0xE9,0xDE,0x44,0xBD,0x0C,0x8E,0x94,0x08,0x1F,0x28,0xBB,0xB9,0xD9,0xC6,0xC5,0xA8,0x83,0xFD,0x3B,0xFB,0xCB,
0x64,0xC9,0x1D,0x2C,0x44,0xDC,0xB1,0x37,0x36,0x8A,0x9A,0x52,0x61,0xCF,0xDA,0x21,0xB5,0x07,0xFB,0x6C,0x28,0x94,0x83,0xE2,0x2F,0xB3,0x53,0x56,0x37,0xEA,0xD2,0x10,
0x7F,0x16,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x92,0xDF,0xF6,0x5D,0x85,0x9B,0xBC,0x1D,0x92,0x13,0xE5,0x3A,0xED,0x02,0x61,0x51,0x4E,0xB0,0x88,0xC6,0xF9,0x88,0x5A,0xC4,0x5E,0xB0,0xAD,0xCA,0x7B,0xAD,0xC4,0xE8,
0xCC,0xF8,0x55,0x8B,0x4B,0x48,0x56,0x72,0x44,0x48,0xC8,0xA2,0xE5,0x93,0xA5,0xDD,0xB3,0x09,0xA6,0xE3,0xD0,0xD9,0xBC,0x7B,0x4B,0x60,0xE4,0xE6,0xB6,0xA6,0xE6,0x2B,
0x1D,0xDE,0x8B,0x17,0x47,0x2B,0xFA,0x6F,0x11,0xE0,0x9E,0xA7,0x22,0xF0,0xCB,0x3A,0x3F,0xC3,0xA4,0xAF,0x18,0x96,0xDB,0x3A,0x98,0x7E,0x5F,0x8A,0xDB,0x99,0x0A,0x31,
0x25,0x2A,0x94,0x21,0x5C,0xE5,0x92,0x76,0x34,0xB9,0x5C,0xB1,0x72,0x49,0x23,0xBF,0xBA,0x93,0xDE,0x94,0x28,0x65,0xD0,0x07,0x17,0x84,0x10,0xDE,0x62,0xF1,0x46,0x98,
0x61,0xF9,0x05,0xAF,0x57,0x4D,0x59,0xE5,0x89,0x10,0x16,0xD6,0x41,0x41,0xFE,0xAA,0x50,0xF8,0xAE,0x74,0x69,0xE4,0xF9,0x2E,0xED,0x35,0xC7,0xED,0x68,0xF9,0x25,0x58,
0x5C,0x19,0x96,0x9B,0xF0,0x7E,0xCE,0x61,0x05,0x45,0x44,0xE0,0x45,0x6C,0x14,0xFE,0x92,0xBB,0x24,0xB9,0xD3,0x7F,0x2B,0x5E,0xFE,0xDB,0xB1,0x4A,0x6A,0xAC,0x53,0x74,
0xA9,0xBF,0xF0,0x02,0x0C,0x08,0xA2,0x45,0x31,0xED,0xBE,0x9A,0x54,0x29,0x30,0xE4,0xA6,0xEE,0xC8,0x62,0x87,0x42,0x32,0x77,0xA2,0xE6,0xAF,0xCC,0x02,0x9F,0xED,0x44,
0xE6,0x59,0xDF,0x8E,0xE6,0x0A,0xC4,0xAC,0x5C,0x30,0x56,0x9A,0xCD,0xBB,0xC6,0x6E,0x93,0xDB,0x25,0xA0,0xFA,0xD2,0xE2,0x00,0x4B,0xCB,0x97,0xA2,0xDC,0xA0,0x81,0x61,
0x4F,0x88,0x76,0x5D,0xB0,0x6B,0x4A,0x0E,0xB9,0x51,0x26,0xAE,0x15,0x9D,0x49,0x8B,0xB8,0x0B,0x26,0x90,0xFE,0xFD,0x17,0x8C,0x2C,0x5E,0x9D,0x2F,0x36,0x46,0x0A,0xDC,
0xF3,0xD2,0x5D,0x3E,0xBA,0x65,0x27,0xE6,0x49,0x2F,0x4D,0x90,0xA9,0x42,0x02,0xE6,0x82,0x70,0x3B,0xD4,0x69,0x6E,0x71,0x18,0x5E,0x69,0x74,0x04,0x6B,0x7A,0x96,0xC2,
0xF4,0x68,0xF4,0x70,0xBD,0x23,0x70,0x3F,0xCC,0x46,0x94,0xF1,0x9E,0x3E,0x1D,0x01,0xC4,0xF4,0x4A,0x1F,0xCE,0x15,0xD5,0xFB,0x3B,0x5C,0x35,0x83,0x74,0x2B,0xDE,0x64,
0xDB,0xD2,0xA7,0xBE,0x74,0x66,0xFF,0x0E,0x50,0xD5,0x20,0xFF,0x0B,0x8D,0x3A,0xC8,0xC2,0x8D,0x90,0x87,0xAE,0xB6,0x58,0x71,0x89,0xF9,0x09,0x57,0x6F,0x36,0x60,0x41,
0xFD,0x54,0xE3,0x5D,0x44,0x00,0x94,0xA6,0xFA,0x54,0x07,0x35,0x41,0x42,0x5C,0x85,0x75,0x7D,0x1F,0x9E,0xD5,0x13,0x16,0x41,0x90,0x75,0x54,0x9F,0x65,0x3E,0xD9,0x71,
0xAC,0x1B,0x59,0x77,0x4C,0xD2,0xE8,0x33,0x65,0xDE,0xD1,0xE1,0x1B,0x0F,0xB5,0x0F,0x4C,0xEB,0x0B,0x3E,0xB4,0x29,0x56,0x0C,0x3B,0x5A,0x19,0x7B,0xCB,0xE3,0x15,0x82,
0x73,0x74,0xB1,0xC7,0x7C,0xDE,0xC7,0x2B,0xB0,0x38,0x7D,0x55,0x2B,0x5C,0x4D,0xC6,0x34,0xF1,0xD2,0xF8,0xBD,0x7A,0xFC,0x3A,0x51,0x32,0x30,0x7A,0xD4,0x34,0xF6,0x27,
0x92,0x10,0xFE,0x40,0x2D,0x80,0x72,0x6B,0xB7,0x94,0xFD,0x32,0x62,0x14,0x04,0x62,0x24,0xD8,0x52,0xCD,0x17,0xD2,0x62,0x05,0x3A,0xDD,0x10,0x6F,0x75,0x94,0xA2,0xCE,
0x37,0x70,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x92,0xDF,0xF6,0x5D,0x85,0x9B,0xBC,0x1D,0x92,0x13,0xE5,0x3A,0xED,0x02,0x61,0x51,0x4E,0xB0,0x88,0xC6,0xF9,0x88,0x5A,0xC4,0x5E,0xB0,0xAD,0xCA,0x7B,0xAD,0xC4,0xE8,
0xCC,0xF8,0x55,0x8B,0x4B,0x48,0x56,0x72,0x44,0x48,0xC8,0xA2,0xE5,0x93,0xA5,0xDD,0xB3,0x09,0xA6,0xE3,0xD0,0xD9,0xBC,0x7B,0x4B,0x60,0xE4,0xE6,0xB6,0xA6,0xE6,0x2B,
0x1D,0xDE,0x8B,0x17,0x47,0x2B,0xFA,0x6F,0x11,0xE0,0x9E,0xA7,0x22,0xF0,0xCB,0x3A,0x3F,0xC3,0xA4,0xAF,0x18,0x96,0xDB,0x3A,0x98,0x7E,0x5F,0x8A,0xDB,0x99,0x0A,0x31,
0x25,0x2A,0x94,0x21,0x5C,0xE5,0x92,0x76,0x34,0xB9,0x5C,0xB1,0x72,0x49,0x23,0xBF,0xBA,0x93,0xDE,0x94,0x28,0x65,0xD0,0x07,0x17,0x84,0x10,0xDE,0x62,0xF1,0x46,0x98,
0x61,0xF9,0x05,0xAF,0x57,0x4D,0x59,0xE5,0x89,0x10,0x16,0xD6,0x41,0x41,0xFE,0xAA,0x50,0xF8,0xAE,0x74,0x69,0xE4,0xF9,0x2E,0xED,0x35,0xC7,0xED,0x68,0xF9,0x25,0x58,
0x5C,0x19,0x96,0x9B,0xF0,0x7E,0xCE,0x61,0x05,0x45,0x44,0xE0,0x45,0x6C,0x14,0xFE,0x92,0xBB,0x24,0xB9,0xD3,0x7F,0x2B,0x5E,0xFE,0xDB,0xB1,0x4A,0x6A,0xAC,0x53,0x74,
0xA9,0xBF,0xF0,0x02,0x0C,0x08,0xA2,0x45,0x31,0xED,0xBE,0x9A,0x54,0x29,0x30,0xE4,0xA6,0xEE,0xC8,0x62,0x87,0x42,0x32,0x77,0xA2,0xE6,0xAF,0xCC,0x02,0x9F,0xED,0x44,
0xE6,0x59,0xDF,0x8E,0xE6,0x0A,0xC4,0xAC,0x5C,0x30,0x56,0x9A,0xCD,0xBB,0xC6,0x6E,0x93,0xDB,0x25,0xA0,0xFA,0xD2,0xE2,0x00,0x4B,0xCB,0x97,0xA2,0xDC,0xA0,0x81,0x61,
0x4F,0x88,0x76,0x5D,0xB0,0x6B,0x4A,0x0E,0xB9,0x51,0x26,0xAE,0x15,0x9D,0x49,0x8B,0xB8,0x0B,0x26,0x90,0xFE,0xFD,0x17,0x8C,0x2C,0x5E,0x9D,0x2F,0x36,0x46,0x0A,0xDC,
0xF3,0xD2,0x5D,0x3E,0xBA,0x65,0x27,0xE6,0x49,0x2F,0x4D,0x90,0xA9,0x42,0x02,0xE6,0x82,0x70,0x3B,0xD4,0x69,0x6E,0x71,0x18,0x5E,0x69,0x74,0x04,0x6B,0x7A,0x96,0xC2,
0xF4,0x68,0xF4,0x70,0xBD,0x23,0x70,0x3F,0xCC,0x46,0x94,0xF1,0x9E,0x3E,0x1D,0x01,0xC4,0xF4,0x4A,0x1F,0xCE,0x15,0xD5,0xFB,0x3B,0x5C,0x35,0x83,0x74,0x2B,0xDE,0x64,
0xDB,0xD2,0xA7,0xBE,0x74,0x66,0xFF,0x0E,0x50,0xD5,0x20,0xFF,0x0B,0x8D,0x3A,0xC8,0xC2,0x8D,0x90,0x87,0xAE,0xB6,0x58,0x71,0x89,0xF9,0x09,0x57,0x6F,0x36,0x60,0x41,
0xFD,0x54,0xE3,0x5D,0x44,0x00,0x94,0xA6,0xFA,0x54,0x07,0x35,0x41,0x42,0x5C,0x85,0x75,0x7D,0x1F,0x9E,0xD5,0x13,0x16,0x41,0x90,0x75,0x54,0x9F,0x65,0x3E,0xD9,0x71,
0xAC,0x1B,0x59,0x77,0x4C,0xD2,0xE8,0x33,0x65,0xDE,0xD1,0xE1,0x1B,0x0F,0xB5,0x0F,0x4C,0xEB,0x0B,0x3E,0xB4,0x29,0x56,0x0C,0x3B,0x5A,0x19,0x7B,0xCB,0xE3,0x15,0x82,
0x73,0x74,0xB1,0xC7,0x7C,0xDE,0xC7,0x2B,0xB0,0x38,0x7D,0x55,0x2B,0x5C,0x4D,0xC6,0x34,0xF1,0xD2,0xF8,0xBD,0x7A,0xFC,0x3A,0x51,0x32,0x30,0x7A,0xD4,0x34,0xF6,0x27,
0x92,0x10,0xFE,0x40,0x2D,0x80,0x72,0x6B,0xB7,0x94,0xFD,0x32,0x62,0x14,0x04,0x62,0x24,0xD8,0x52,0xCD,0x17,0xD2,0x62,0x05,0x3A,0xDD,0x10,0x6F,0x75,0x94,0xA2,0xCE,
0x37,0x70,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};`

Any chance someone can share a working dump?

**Comment by Nickduino** [comment]
And proof I'm actually working on my cartridge and not trying to sell dumps online or whatever:

![image](https://github.com/wangyu-/canon_mc-g02_resetter/assets/9784237/9525f956-09d5-49da-9013-40e15b1bd970)

**Comment by Nickduino** [comment]
And again, I'm sorry for being an idiot and not checking the dump, I rushed it.

**Comment by Nickduino** [comment]
I just took a look at the code. You write the dump **without modifying it** to reset the counter? So it works only if you have a dump from a fresh maintenance cartridge (which I don't)?

**Comment by wangyu-** [comment]
>You write the dump without modifying it to reset the counter? 

You are right, reset means "reset to the point you dump it".

>I'm an idiot for not double checking my dump when reading it (I know the instructions call for that). Now I wrote the wrong dump and I obviously can't read it anymore. The printer doesn't recognize the cartridge.
>Any chance someone can share a working dump?

someone shared his dump of mc-g01 in https://github.com/wangyu-/canon_mc-g02_resetter/issues/2

**Comment by wangyu-** [comment]
> So it works only if you have a dump from a fresh maintenance cartridge (which I don't)?

It should still reset the chip to the moment you dump it, even if it's not a fresh cartridage.

>The printer doesn't recognize the cartridge.

For your case, if it doesn't recongnize at all, it's likely a bad dump or bad write.

**Comment by Nickduino** [comment]
Solved with https://github.com/wangyu-/canon_mc-g02_resetter/issues/2#issuecomment-1760524409

Thanks!
